def sanitize_llm_response(raw_text):
    """Clean markdown remnants or conversational filler from Ollama."""
    if not raw_text:
        return "No descriptive log generated by AI."
    
    cleaned = raw_text.strip()
    # Strip common LLM markdown response wrappers if present
    if cleaned.startswith("```"):
        cleaned = "\n".join(cleaned.split("\n")[1:-1])
    
    return cleaned.replace('"', '').strip()
